name: "extender:stage channel:beta"

on:
  check_suite:
    types: [rerequested]
  schedule:
    - cron: 0 6 * * *

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      channel: beta
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
