name: "extender:stage channel:stable"

on:
  schedule:
    - cron: 0 11 * * *

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      channel: stable
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
